### ISSUE TITLE
Field 'base_CircularApertureFlux_2_flux' not found in Schema.

### ISSUE THREAD

**Issue by JPGlaser** [lsst/lsst_dm_stack_demo#1]
To Whom it May Concern,

I've been attempting to get the lsst_dm_stack_demo code to work on my end for a test of the recent install on our cluster. The following error has appeared after running the code as suggested in the documentation:

```bash
[...]
processCcd: Matching icSource and Source catalogs to propagate flags.
CameraMapper: Loading registry registry from output_small/_parent/registry.sqlite3
Traceback (most recent call last):
  File "./bin/export-results", line 106, in <module>
    v = srcs.get(col)
  File "/home/jglaser/lsst/Linux64/afw/10.0+3/python/lsst/afw/table/tableLib.py", line 10286, in get
    return self[k]
  File "/home/jglaser/lsst/Linux64/afw/10.0+3/python/lsst/afw/table/tableLib.py", line 10218, in __getitem__
    return self.columns[k]
  File "/home/jglaser/lsst/Linux64/afw/10.0+3/python/lsst/afw/table/tableLib.py", line 3015, in __getitem__
    return self[self.schema.find(args[0]).key]
  File "/home/jglaser/lsst/Linux64/afw/10.0+3/python/lsst/afw/table/tableLib.py", line 1040, in find
    raise KeyError("Field '%s' not found in Schema." % k)
KeyError: "Field 'base_CircularApertureFlux_2_flux' not found in Schema."
```

Has anyone seen this before?

**Comment by TallJimbo** [comment]
I would guess this is a version mismatch between the demo package and the version of the pipeline you're using.  You probably need to check out a tagged version of the latter that matches the version of the former.

**Comment by JPGlaser** [comment]
Huh, that would be odd as I have v10_0 of the base install pulled down and installed correctly. I just attempted to pull down the latest version stored on github and it looks like error is still manifesting. Is there anywhere that I can see the tagged versions of the demo to make sure that they are the same for my version of lsst?

**Comment by TallJimbo** [comment]
Unfortunately, it looks like the demo package never got tagged for 10.0, so I don't think there's an easy answer to this (we'll see if someone who has paid more attention to the demo package and/or regular install issues than I have replies).  The master version of the stack - which is what the latest version of the demo package on GitHub corresponds to - is well ahead of 10.0 at this point, so I wouldn't expect the demo package to work with that.  I do see tags for versions earlier than 8.0, but overall we'd done a poor job of trying to keep the demo package integrated with the rest of the stack; we're aware it's a problem, but it hasn't risen to the top of anyone's priority list.

**Comment by RobertLuptonTheGood** [comment]
Is there any reason why we cannot include the demo package as part of continuous integration?  Frossie's on a (traumatic? --- don't say "National Park Passport" to her) road trip, but I imagine she'll weigh in at some point.

						R

**Comment by TallJimbo** [comment]
Just lack of effort, I think: https://jira.lsstcorp.org/browse/DM-1357

**Comment by JPGlaser** [comment]
Thanks for the info @TallJimbo, I was trying to figure out exactly what was going on there with regard to the lack of versions tagged here on GitHub. This does raise the question on my end since I've been getting a few errors here and there with other scripts, how do I know which versions are the most recent with regards to the masters-<alpha-numeric tag> versions listed in eups, or more importantly, which versions match which?

In addition, is the https://confluence.lsstcorp.org/ site still the most relevant section for documentation?

~ Joe

**Comment by TallJimbo** [comment]
Confluence still the best place for this sort of documentation (though it may not be forever), but I imagine it will improve considerably in the next couple weeks as we put out a new release - new releases are the times those pages see the most attention.  In terms of getting more interactive help, you'll probably get a better response by sending email to dm-users@lists.lsst.org; I'm not sure how many people are watching all of these repositories.

The question of which versions match which others is probably best handled by installing one of the metapackages, such as `lsst_apps` or `lsst_sims`; those will automatically install the correct versions of a whole lot of packages together.  The fact that the master versions don't sort is, I'm afraid, another known issue: https://jira.lsstcorp.org/browse/DM-2169.

**Comment by JPGlaser** [comment]
Thanks for the clarification on both counts @TallJimbo. My main goal over here at Drexel is to get the lsst_sims package up and running on our local cluster so we can start transitioning away form SDSS images to theoretically better simulated analogs. Though that seems to be a bit of a slow go as getting all of the parts talking to each other seems to be a bit difficult with v10.0.

I did notice that it looks like the framework is moving slightly away from the varied shell languages and towards a python interpreter, which looks rather nice overall. Is there a planned release time-frame set up for the master version?

Also you mentioned that these repos aren't being watched as vigorously, so is there a git location that LSST Coorp is more "active" on?

Thanks again for all your help thus far!

~ Joe

**Comment by TallJimbo** [comment]
I'm not actually that familiar with what the sims team is doing, but on the DM side we've been using Python scripts pretty much exclusively from the beginning, so I'm not surprised to hear they're moving that way.

I believe we have a release candidate out already for the next release, and while we don't have a hard schedule, I'd be surprised if it takes longer than a month from now to get the official release out the door.

These are indeed our main GitHub repos for code, but we don't use them for issues regularly - there are so many of them that many developers may not watch most of them for changes, relying on our unified JIRA issue tracker (https://jira.lsstcorp.org/browse/DM/) and GitHub @-mentions to know when they should be paying attention.

**Comment by JPGlaser** [comment]
Thanks again for that info, @TallJimbo. I am looking forward to the new release of the stack. I'll look into getting access to JIRA from my advisor (Dr. G. Richards @ Drexel University) so that I can direct any more issues there as they occur. The good news is that it looks like the issues I have been having with OpSim (which seems to not be located on GitHub) and CatSim (lsst_sims) seem to mostly be handled, so the LSST stack install seems to be working correctly sans this demo error (which as we mentioned, is likely due to a version mismatch). Hopefully, the version management bug for the masters can be handled without too much trouble down the line. Again, thanks very much for all the help everyone!

~ Joe

**Comment by timj** [comment]
Starting with v11.0 the demo is now tagged with the release so this issue should not recur.
